//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FBE.rc
//
#define IDOK3                           2
#define IDUPDATE                        2
#define IDOK2                           3
#define IDD_ABOUTBOX                    100
#define ID_VIEW_TREE                    101
#define IDS_PANE_INS                    102
#define IDS_PANE_OVR                    103
#define IDS_DOC_TREE_CLEANUP            104
#define IDN_WANTFOCUS                   105
#define IDS_HOTKEY_FILE_OPEN            105
#define IDS_HOTKEY_FILE_SAVE            106
#define IDS_HOTKEY_FILE_SAVEAS          107
#define IDD_PROPPAGE_LARGE              107
#define IDS_HOTKEY_FILE_VALIDATE        108
#define IDS_HOTKEY_GROUP_FILE           109
#define IDN_ED_TEXT                     110
#define IDS_HOTKEY_EDIT_ADD_ANNOTATION  110
#define IDR_EXTRAICONS                  111
#define IDS_HOTKEY_EDIT_ADD_BODY        111
#define IDS_HOTKEY_EDIT_ADD_EPIGRAPH    112
#define IDS_HOTKEY_EDIT_ADD_IMAGE       113
#define IDN_DOC_LOADED                  114
#define IDS_HOTKEY_EDIT_ADD_TABLE       114
#define IDS_HOTKEY_EDIT_ADD_TA          114
#define IDN_SEL_CHANGE                  115
#define IDS_HOTKEY_EDIT_ADD_TITLE       115
#define IDN_ED_CHANGED                  116
#define IDS_HOTKEY_EDIT_BOLD            116
#define IDN_TREE_DELETE_ELEMENT         117
#define IDS_HOTKEY_EDIT_CLONE           117
#define IDD_REPLACE                     118
#define IDS_HOTKEY_EDIT_COPY            118
#define IDN_TREE_RIGHT                  119
#define IDS_HOTKEY_EDIT_CUT             119
#define IDN_NAVIGATE                    120
#define IDS_HOTKEY_EDIT_FIND            120
#define IDN_TREE_LEFT                   121
#define IDS_HOTKEY_EDIT_FIND_NEXT       121
#define IDN_FAST_MODE_CHANGE            122
#define IDS_HOTKEY_EDIT_INCREMENTAL_SEARCH 122
#define IDS_HOTKEY_EDIT_INSERT_CITE     123
#define IDN_HKMAP_CHANGE                124
#define IDS_HOTKEY_EDIT_INSERT_IMAGE    124
#define IDS_HOTKEY_EDIT_INSERT_POEM     125
#define ID_EDIT_REMOVE_OUTER_SECTION    126
#define IDS_HOTKEY_EDIT_ITALIC          126
#define ID_VIEW_SOURCE                  127
#define IDR_MAINFRAME                   128
#define IDB_CUSTOMSTATIC                129
#define IDS_SB_NO_ERR                   129
#define IDR_CUSTOMSTATIC                130
#define IDS_DMS_TI                      130
#define IDS_LANG_ENGLISH                131
#define IDS_LANG_RUSSIAN                132
#define IDS_DMS_GENRE_M                 133
#define IDS_DMS_KW                      134
#define IDS_DMS_AUTHOR                  135
#define IDS_DMS_DI                      136
#define IDS_DMS_ID                      137
#define IDS_DMS_STI                     138
#define IDS_DMS_CI                      139
#define IDS_SETTINGS_VIEW_CAPTION       140
#define IDS_SETTINGS_OTHER_CAPTION      141
#define IDS_TB_CAPT_ID                  142
#define IDS_TB_CAPT_HREF                143
#define IDS_TB_CAPT_SECTION_ID          144
#define IDS_TB_CAPT_IMAGE_TITLE         145
#define IDS_TB_CAPT_TABLE_ID            146
#define IDS_TB_CAPT_TABLE_STYLE         147
#define IDS_TB_CAPT_STYLE               148
#define IDS_TB_CAPT_COLSPAN             149
#define IDS_TB_CAPT_ROWSPAN             150
#define IDS_TB_CAPT_TR_ALIGN            151
#define IDS_TB_CAPT_TD_ALIGN            152
#define IDS_TB_CAPT_TD_VALIGN           153
#define IDS_SAVE_DLG_MSG                154
#define IDS_ERRMSGBOX_CAPTION           155
#define IDS_INVALID_CML_MSG             156
#define IDS_CML_ARGS_MSG                157
#define IDS_SEARCH_END_MSG              158
#define IDS_REPL_ALL_CAPT               159
#define IDS_REPL_DONE_MSG               160
#define IDS_SEARCH_FAIL_MSG             161
#define IDS_SCRIPT_MSG_CPT              162
#define IDS_GENRES_LIST_MSG             163
#define IDS_VALIDATION_FAIL_MSG         164
#define IDS_VALIDATION_FAIL_CPT         165
#define IDS_OUT_OF_MEM_MSG              166
#define IDS_SCINTILLA_LOAD_ERR_MSG      167
#define IDS_GOTO_REF_FAIL_MSG           168
#define IDS_IMPORT_ERR_CPT              169
#define IDS_IMPORT_ERR_MSG              170
#define IDS_IMPORT_XML_ERR_MSG          171
#define IDS_EXPORT_ERR_CPT              172
#define IDS_EXPORT_ERR_MSG              173
#define IDS_FILE_CHANGED_CPT            174
#define IDS_FILE_CHANGED_MSG            175
#define IDS_SCRIPT_ERRX_MSG             176
#define IDS_SCRIPT_ERRD_MSG             177
#define IDS_SCRIPT_MSG                  178
#define IDS_SCRIPT_LOAD_ERR_MSG         179
#define IDS_COM_ERR_CPT                 180
#define IDS_XML_PARSE_ERR_CPT           181
#define IDS_XML_PARSE_ERR_MSG           182
#define IDS_XML_PARSE_ERRQ_MSG          183
#define IDS_REPL_WORDS_CPT              184
#define IDS_REPL_WORDS_MSG              185
#define IDS_NO_SCRIPTS                  186
#define IDS_SB_SAVED_NO_ERR             187
#define IDS_ADD_CLEARIMG_TEXT           188
#define IDS_ADD_CLEARIMG_CAPTION        189
#define IDS_ADD_IMAGE_FILEDLG           190
#define IDS_ADD_IMAGE_FILEDLG2          191
#define IDS_ADD_BINARIES_FILEDLG        191
#define IDS_CHOOSE_SCRIPTS_FLD          192
#define IDS_SCRIPT_HOTKEY_CONFLICT      193
#define IDS_HOTKEY_EDIT_MERGE           194
#define IDS_HOTKEY_EDIT_PASTE           195
#define IDS_HOTKEY_EDIT_REDO            196
#define IDS_HOTKEY_EDIT_REPLACE         197
#define IDS_HOTKEY_EDIT_SPLIT           198
#define IDS_HOTKEY_EDIT_UNDO            199
#define IDS_HOTKEY_GROUP_EDIT           200
#define IDB_STRUCTURE                   201
#define IDS_HOTKEY_GROUP_NAVIGATION     201
#define IDD_INPUTBOX                    202
#define IDS_HOTKEY_NAVIGATION_GOTO_REFERENCE 202
#define IDS_UPDATE_CHECK                202
#define IDS_HOTKEY_NAVIGATION_NEXT_ITEM 203
#define ID_PANE_INS                     204
#define IDS_HOTKEY_NAVIGATION_SCI_COLLAPSE1 205
#define IDS_HOTKEY_NAVIGATION_SCI_COLLAPSE2 206
#define IDS_HOTKEY_NAVIGATION_SCI_COLLAPSE3 207
#define IDS_HOTKEY_NAVIGATION_SCI_COLLAPSE4 208
#define IDS_HOTKEY_NAVIGATION_SCI_COLLAPSE5 209
#define IDS_HOTKEY_NAVIGATION_SCI_COLLAPSE6 210
#define IDD_OPTIONS                     211
#define IDS_HOTKEY_NAVIGATION_SCI_COLLAPSE7 211
#define IDS_HOTKEY_NAVIGATION_SCI_COLLAPSE8 212
#define IDS_HOTKEY_NAVIGATION_SCI_COLLAPSE9 213
#define IDS_HOTKEY_NAVIGATION_SCI_EXPAND1 214
#define IDS_HOTKEY_NAVIGATION_SCI_EXPAND2 215
#define IDS_HOTKEY_NAVIGATION_SCI_EXPAND3 216
#define IDS_HOTKEY_NAVIGATION_SCI_EXPAND4 217
#define IDS_HOTKEY_NAVIGATION_SCI_EXPAND5 218
#define IDS_HOTKEY_NAVIGATION_SCI_EXPAND6 219
#define IDS_HOTKEY_NAVIGATION_SCI_EXPAND7 220
#define IDS_HOTKEY_NAVIGATION_SCI_EXPAND8 221
#define IDS_HOTKEY_NAVIGATION_SCI_EXPAND9 222
#define IDD_FIND                        223
#define IDS_HOTKEY_NAVIGATION_SELECT_HREF 223
#define IDS_HOTKEY_NAVIGATION_SELECT_ID 224
#define IDS_HOTKEY_NAVIGATION_SELECT_ID_TABLE 225
#define IDS_HOTKEY_NAVIGATION_SELECT_TEXT 226
#define IDD_CUSTOMSAVEDLG               227
#define IDS_HOTKEY_NAVIGATION_SELECT_TREE 227
#define IDD_WORDS                       228
#define IDS_HOTKEY_GROUP_STYLE          228
#define IDB_WORDSTATES                  229
#define IDS_HOTKEY_STYLE_LINK           229
#define IDS_HOTKEY_STYLE_NO_LINK        230
#define IDD_TABLE                       231
#define IDS_HOTKEY_STYLE_NORMAL         231
#define IDS_HOTKEY_STYLE_NOTE           232
#define IDS_HOTKEY_STYLE_SUBTITLE       233
#define IDR_MAINFRAME_SMALL             234
#define IDS_HOTKEY_STYLE_TEXT_AUTHOR    234
#define IDS_HOTKEY_GROUP_VIEW           235
#define IDS_HOTKEY_VIEW_BODY            236
#define IDI_OPEN                        237
#define IDS_HOTKEY_VIEW_DESCRIPTION     237
#define IDS_HOTKEY_VIEW_SOURCE          238
#define IDR_DOCUMENT_TREE               239
#define IDS_HOTKEY_EDIT_INSERT_TABLE    239
#define IDR_ACCELERATOR1                240
#define IDS_HOTKEY_GROUP_SCRIPTS        240
#define IDS_HOTKEY_SCRIPTS_LAST_SCRIPT  241
#define IDD_TOOLS_SETTINGS              242
#define IDS_SETTINGS_HOTKEYS_CAPTION    242
#define IDS_STRING243                   243
#define IDS_HOTKEY_GROUP_SYMBOLS        243
#define IDD_SETTING_OTHER               244
#define IDS_HOTKEY_SYMBOL_ACUTE_ACCENT  244
#define IDS_SETTINGS_WORDS_CAPTION      244
#define IDS_HOTKEY_SYMBOL_QUOTATION_MARK 245
#define IDS_SETTINGS_WLIST_COUNTED      245
#define IDS_HOTKEY_SYMBOL_DEGREE_SIGN   246
#define IDS_SETTINGS_WLIST_WORD         246
#define IDS_HOTKEY_SYMBOL_SUPERSCRIPT_ONE 247
#define IDS_SETTINGS_WORDS_ADD_ERR_TEXT 247
#define IDB_BITMAP1                     248
#define IDB_AB_BANNER                   248
#define IDS_HOTKEY_SYMBOL_SUPERSCRIPT_TWO 248
#define IDS_SETTINGS_WORDS_ADD_ERR_CAP  248
#define IDD_ADDIMAGE                    249
#define IDS_HOTKEY_SYMBOL_SUPERSCRIPT_THREE 249
#define IDS_SETTINGS_WORDS_ADD_ERR_SYM  249
#define IDD_HOTKEYS                     250
#define IDS_HOTKEY_SYMBOL_MULTIPLICATION_SIGN 250
#define IDS_WORDS_WLIST_WORD            250
#define IDS_HOTKEY_SYMBOL_DIVISION_SIGN 251
#define IDD_SETTINGS_WORDS              251
#define IDS_WORDS_WLIST_REPLACEMENT     251
#define IDS_HOTKEY_SYMBOL_LEFT_SINGLE_QUOTATION_MARK 252
#define IDS_WORDS_WLIST_COUNTED         252
#define IDS_HOTKEY_SYMBOL_RIGHT_SINGLE_QUOTATION_MARK 253
#define IDS_WORDS_FR_BTN_FIND0          253
#define IDD_SPELL_CHECK                 253
#define IDS_HOTKEY_SYMBOL_LEFT_DOUBLE_QUOTATION_MARK 254
#define IDS_WORDS_FR_BTN_FIND1          254
#define IDR_MENU1                       254
#define IDR_TOOLBAR_MENU                254
#define IDS_HOTKEY_SYMBOL_RIGHT_DOUBLE_QUOTATION_MARK 255
#define IDS_CTXMENU_CUT                 255
#define IDI_ICON1                       255
#define IDI_OLDICON                     255
#define IDS_HOTKEY_SYMBOL_LEFT_POINTING_DOUBLE_QUOTATION_MARK 256
#define IDS_CTXMENU_COPY                256
#define IDS_HOTKEY_SYMBOL_RIGHT_POINTING_DOUBLE_QUOTATION_MARK 257
#define IDS_CTXMENU_PASTE               257
#define IDS_HOTKEY_SYMBOL_HORIZONTAL_ELLIPSIS 258
#define IDS_CTXMENU_SELECT              258
#define IDS_HOTKEY_SYMBOL_EN_DASH       259
#define IDS_CTXMENU_IMG_SAVEAS          259
#define IDS_HOTKEY_SYMBOL_EM_DASH       260
#define IDS_UPDATE_CONNECTING           260
#define IDS_HOTKEY_WRONG                261
#define IDS_HOTKEY_DEFAULT_COLLISION    262
#define IDS_HOTKEY_ASSIGN_NO_COLLISION  263
#define IDS_HOTKEY_ASSIGN_COLLISION     264
#define IDS_SETTINGS_NEED_RESTART       265
#define IDS_DOCTREE_MENU_ELEMENTS       266
#define IDS_DOCTREE_MENU_SCRIPTS        267
#define IDS_HOTKEY_EDIT_REMOVE_OUTER_SECTION 268
#define IDS_HOTKEY_GROUP_TOOLS          269
#define IDS_HOTKEY_TOOLS_WORDS          270
#define IDS_HOTKEY_GROUP_PLUGINS        271
#define IDS_HOTKEY_PLUGINS_LAST_PLUGIN  272
#define IDS_HOTKEY_TOOLS_SPELL          273
#define IDC_SPELL_ADD2DICT              274
#define IDS_SPELL_CHECK_COMPLETED       275
#define IDS_SPELL_COMPLETED             275
#define IDC_SPELL_IGNOREALL             276
#define IDS_SPELLCHECK_CONTINUE         277
#define IDS_SPELL_CONTINUE              277
#define IDS_HOTKEY_EDIT_INSERT_INLINEIMAGE 278
#define IDS_HOTKEY_EDIT_PASTE2          279
#define IDS_UPDATE_CANTCONNECT          279
#define IDS_HOTKEY_FASTMODE             280
#define IDS_HOTKEY_TREEVIEW             281
#define IDS_HOTKEY_TOOLS_SPELLHIGHLIGHT 282
#define IDS_HOTKEY_NAVIGATION_GOTO_FOOTNOTE 283
#define IDS_HOTKEY_NAVIGATION_GOTO_MATCHTAG 284
#define IDS_HOTKEY_NAVIGATION_GOTO_WRONGTAG 285
#define IDR_SCRIPTS                     286
#define IDS_UPDATE_DOWNLOADEDFROM       286
#define IDB_UPD_OK                      287
#define IDS_UPDATE_DOWNLOADED           287
#define IDB_UPD_ERR                     288
#define IDS_UPDATE_DOWNLOADCOMPLETE     288
#define IDB_UPD_UPDATE                  289
#define IDS_UPDATE_DOWNLOADERROR        289
#define IDS_UPDATE_404ERROR             290
#define IDS_UPDATE_403ERROR             291
#define IDS_UPDATE_407ERROR             292
#define IDS_UPDATE_NOTSUPPORTEDRANGE    293
#define IDS_UPDATE_DOWNLOADERRORSTATUS  294
#define IDS_UPDATE_INCORRECTMD5         295
#define IDS_UPDATE_NEWVERSIONAVAILABLE  296
#define IDS_UPDATE_HAVELATESTVERSION    297
#define IDS_ABOUT_LOGOCAPTION           298
#define IDS_UPDATE_CLOSE                299
#define IDS_LANG_UKRAINIAN              300
#define IDS_UPDATEEXISTS                301
#define IDS_UPDATE_DOWNLOADREADY        302
#define IDS_BAD_XML_MSG                 303
#define IDS_HOTKEY_EDIT_SUB             304
#define IDS_HOTKEY_EDIT_SUP             305
#define ID_PANE_CHAR                    305
#define IDB_UPD_CHECK1                  400
#define IDB_UPD_CHECK2                  401
#define IDB_UPD_CHECK3                  402
#define IDB_UPD_CHECK4                  403
#define IDB_UPD_CHECK5                  404
#define IDB_UPD_CHECK6                  405
#define IDB_UPD_CHECK7                  406
#define IDB_UPD_CHECK8                  407
#define IDB_UPD_CHECK9                  408
#define IDB_UPD_CHECK10                 409
#define IDB_UPD_CHECK11                 410
#define IDB_UPD_CHECK12                 411
#define IDB_UPD_CHECK13                 412
#define IDB_UPD_CHECK14                 413
#define IDB_UPD_CHECK15                 414
#define IDB_UPD_CHECK16                 415
#define IDB_UPD_CHECK17                 416
#define IDB_UPD_CHECK18                 417
#define IDB_UPD_CHECK19                 418
#define IDB_UPD_CHECK20                 419
#define IDB_UPD_CHECK21                 420
#define IDB_UPD_CHECK22                 421
#define IDB_UPD_CHECK23                 422
#define IDB_UPD_CHECK24                 423
#define IDC_SPELL_REPLACE               500
#define ID_VER_ADVANCE                  550
#define IDS_MB_OK                       600
#define IDS_MB_CANCEL                   601
#define IDS_MB_ABORT                    602
#define IDS_MB_RETRY                    603
#define IDS_MB_IGNORE                   604
#define IDS_MB_YES                      605
#define IDS_MB_NO                       606
#define IDS_MB_CLOSE                    607
#define IDB_CENTER                      700
#define IDB_ORANGE                      701
#define IDB_GREEN                       702
#define IDB_DOC                         703
#define IDB_XML                         704
#define IDB_OTHER                       705
#define IDB_HTML                        706
#define IDB_PRC                         707
#define IDB_TEXT                        708
#define ID_EXPORT_BASE                  860
#define ID_IMPORT_BASE                  880
#define ID_SEL_BASE                     900
#define IDC_INPUT                       1000
#define IDC_PROMPT                      1001
#define IDC_HREF                        1003
#define IDC_REPLACE_ALL                 1005
#define IDC_REPLACE_ONE                 1006
#define IDC_ID                          1008
#define IDC_FG                          1012
#define IDC_BG                          1013
#define IDC_DICTPATH                    1014
#define IDC_FONT                        1015
#define IDC_FONT_SIZE                   1016
#define IDC_TEXT                        1017
#define IDC_SRCFONT                     1017
#define IDC_REPLACE                     1018
#define IDC_MATCHCASE                   1019
#define IDC_REGEXP                      1020
#define IDC_UP                          1021
#define IDC_DOWN                        1022
#define IDC_BUILDSTAMP                  1023
#define IDC_WHOLE                       1023
#define IDC_ENCODING                    1024
#define IDC_WLIST                       1025
#define IDC_REDIT                       1026
#define IDC_WRAP                        1027
#define IDC_SYNTAXHL                    1028
#define IDC_SHOWEOL                     1029
#define IDC_SHOWLINENUMBERS             1030
#define IDC_STYLE                       1031
#define IDC_TAGHL                       1031
#define IDC_COLSPAN                     1032
#define IDC_SHOWWHITESPACE              1032
#define IDC_ROWSPAN                     1033
#define IDC_ALIGN                       1034
#define IDC_VALIGN                      1035
#define IDC_STYLET                      1036
#define IDC_ALIGNTR                     1037
#define IDC_CHECK_TABLE_TITLE           1038
#define IDC_EDIT_TABLE_ROWS             1039
#define IDC_SPIN_TABLE_ROWS             1040
#define IDC_SECTION                     1041
#define IDC_IMAGE_TITLE                 1042
#define IDC_TAB_CTRL                    1042
#define IDC_SHORTCUTS                   1045
#define IDC_RADIO_KEEP                  1047
#define IDC_RADIO_ALWAYS                1048
#define IDC_ENCODING_ALWAYS             1049
#define IDC_CHECK1                      1050
#define IDC_ENCODING_NEW                1050
#define IDC_SELECT_SCRIPTS_FOLDER_BUTTON 1050
#define IDC_ADDIMAGE_ASKAGAIN           1050
#define IDC_CHECK_DETECT_ONLY_HYPHENED  1050
#define IDC_CHECK_SHOW_EXCLUSIONS       1050
#define IDC_CHECK_SHOWHIDE_EXCLS        1050
#define IDC_KEEP                        1051
#define IDC_DEFAULT_ENC                 1052
#define IDC_CHECK2                      1053
#define IDC_RESTORE_POS                 1053
#define IDC_CHECK_DETECT_PER_P          1053
#define IDC_BACKGROUNDSPELLCHECK        1053
#define IDC_LANG                        1054
#define IDC_SHOW_NBSP                   1054
#define IDC_DEFAULT_SCRIPTS_FOLDER      1055
#define IDC_USESPELLCHECKER             1055
#define IDC_SCRIPTS_FOLDER_PATH         1056
#define IDC_SYSLINK_AB_LINKS            1058
#define IDC_STATIC_APPNAMEVER           1059
#define IDC_STATIC_AB_APPNAMEVER        1059
#define IDC_STATIC_AB_APPICON           1060
#define IDC_STATIC_AB_CONTRIBUTORS      1061
#define IDC_STATIC_AB_APPICON2          1061
#define IDC_STATIC_UPD                  1061
#define IDC_PIC_UPDATE                  1061
#define IDC_AB_BANNER                   1062
#define IDC_CHECK3                      1063
#define IDC_SETTINGS_ASKIMAGE           1063
#define IDC_CHECK_SELALL                1063
#define IDC_CHECK4                      1064
#define IDC_SCRIPTS_HK_NOTIFY           1064
#define IDC_ADDIMAGE_ICON               1065
#define IDC_OPTIONS_CLEARIMGS           1066
#define IDC_STATIC_AB_LINKS             1066
#define IDC_CHANGE_KEYB                 1067
#define IDC_LIST1                       1068
#define IDC_LIST_HOTKEYS_GROUPS         1068
#define IDC_SPELL_SUGG_LIST             1068
#define IDC_LIST2                       1069
#define IDC_LIST_HOTKEYS                1069
#define IDC_EDIT1                       1070
#define IDC_EDIT_HOTKEY                 1070
#define IDC_EDIT_NEW                    1070
#define IDC_SPELL_BEDWORD               1070
#define IDC_SPELL_CUSTOMDICT            1070
#define IDC_CUSTOM_DICT                 1070
#define IDC_CONTRIBS                    1070
#define IDC_JPEGQUALITY                 1070
#define IDC_BUTTON1                     1071
#define IDC_BUTTON_DEFAULT              1071
#define IDC_BUTTON_ADD                  1071
#define IDC_WORDS_FR_EDIT_REPL          1071
#define IDC_NEW_WORD                    1071
#define IDC_SPELL_REPLACEMENT           1071
#define IDC_STATIC_HOTKEY_DESCRIPTION   1072
#define IDC_EDIT_LV                     1072
#define IDC_BUTTON_DESEL                1072
#define IDC_EDIT_HOTKEY_DESCRIPTION     1073
#define IDC_STATIC_HOTKEYS_GROUPS       1074
#define IDC_STATIC_HOTKEYS              1075
#define IDC_BUTTON_HOTKEY_DELETE        1076
#define IDC_BUTTON_HOTKEY_ASSIGN        1077
#define IDC_EDIT_HOTKEY_COLLISION       1078
#define IDC_STATIC_HOTKEY_COLLISION     1079
#define IDC_STATIC_HOTKEY_ACTIONS       1080
#define IDC_COMBOBOXEX1                 1081
#define IDC_LIST_WORDS                  1084
#define IDC_STATIC_WORDS_CHEVRON        1085
#define IDC_BUTTON_REMOVESEL            1086
#define IDC_BUTTON_REMOVEHLREPL         1087
#define IDC_BUTTON_ADDHLTOEXCLS         1088
#define IDC_BUTTON_SELALL               1089
#define IDC_BUTTON_SETHLREPL            1090
#define IDC_BUTTON_SELALL2              1091
#define IDC_BUTTON_SELALLREPL           1091
#define IDC_WORDS_FR_BTN_FIND           1092
#define IDC_WORDS_FR_BTN_REPL           1093
#define IDC_WORDS_FR_GBOX_CURWORD       1094
#define IDC_WORDS_FR_TEXT_WORD          1095
#define IDC_WORDS_FR_EDIT_WORD          1096
#define IDC_WORDS_FR_TEXT_REPL          1097
#define IDC_SPELL_IGNORE                1098
#define IDS_SPELL_CUSTOM_DICT           1099
#define IDC_NBSP_CHAR                   1100
#define IDC_IMAGETYPE                   1101
#define IDC_EDIT3                       1102
#define IDC_IMAGETYPE2                  1102
#define IDC_KEYB_LAYOUT                 1102
#define IDC_SPELL_CHANGE                1103
#define IDC_JPEGSPIN                    1103
#define IDC_SPELL_CHANGEALL             1104
#define ID_FIND_NEXT                    1104
#define IDC_TEXT_STATUS                 1105
#define IDC_TEXT_HTTP_STATUS            1105
#define IDC_UPDATE                      1106
#define IDC_SPELL_ADD                   1107
#define IDB_UPD_CHECK                   1107
#define IDB_UPD_IMAGE                   1107
#define IDC_SPELL_SUGGEST               1108
#define IDC_STATIC_BUILD                1108
#define IDC_SPELL_UNDO                  1109
#define IDC_FAST_MODE                   1110
#define IDC_IDT                         1111
#define IDC_AB_STATIC_BANNER            1112
#define ID_SCRIPT_BASE                  9000
#define ID_EDIT_INS_SYMBOL              10000
#define ID_NEXT_ITEM                    32772
#define ID_SELECT_TREE                  32773
#define ID_EDIT_BOLD                    32779
#define ID_EDIT_ITALIC                  32780
#define ID_STYLE_NORMAL                 32788
#define ID_STYLE_TEXTAUTHOR             32789
#define ID_STYLE_SUBTITLE               32790
#define ID_VIEW_OPTIONS                 32794
#define ID_SELECT_ID                    32796
#define ID_SELECT_HREF                  32797
#define ID_SELECT_TEXT                  32798
#define ID_STYLE_LINK                   32800
#define ID_STYLE_NOTE                   32801
#define ID_EDIT_FINDNEXT                32803
#define ID_EDIT_INCSEARCH               32808
#define ID_VIEW_DESC                    32809
#define ID_VIEW_BODY                    32810
#define ID_VIEW_HTML                    32811
#define ID_STYLE_NOLINK                 32812
#define ID_EDIT_ADDBINARY               32813
#define ID_EDIT_ADD_TITLE               32817
#define ID_EDIT_ADD_BODY                32818
#define ID_EDIT_CLONE                   32819
#define ID_EDIT_INS_IMAGE               32820
#define ID_EDIT_INS_INLINEIMAGE         32821
#define ID_FILE_VALIDATE                32822
#define ID_EDIT_ADD_EPIGRAPH            32824
#define ID_EDIT_ADD_IMAGE               32827
#define ID_EDIT_ADD_ANN                 32829
#define ID_EDIT_SPLIT                   32830
#define ID_EDIT_INS_POEM                32831
#define ID_EDIT_ADD_TA                  32832
#define ID_EDIT_MERGE                   32833
#define ID_TOOLS_OPTIONS                32834
#define ID_TOOLS_WORDS                  32835
#define ID_EDIT_INS_CITE                32836
#define ID_TOOLS_SCRIPTS                32837
#define ID_EDIT_STRIK                   32840
#define ID_EDIT_SUB                     32841
#define ID_EDIT_SUP                     32842
#define ID_EDIT_CODE                    32844
#define ID_SELECT_IDT                   32845
#define ID_SELECT_STYLE                 32846
#define ID_SELECT_COLSPAN               32847
#define ID_SELECT_ROWSPAN               32848
#define ID_SELECT_ALIGN                 32849
#define ID_SELECT_VALIGN                32850
#define ID_SELECT_STYLET                32851
#define ID_SELECT_ALIGNTR               32852
#define ID_INSERT_TABLE                 32853
#define ID_SELECT_SECTION               32854
#define ID_GOTO_FOOTNOTE                32855
#define ID_GOTO_REFERENCE               32856
#define ID_SELECT_IMAGE                 32857
#define ID_DT_RIGHT                     32863
#define ID_DOCUMENT_TREE_CUT            32864
#define ID_DOCUMENT_TREE_PASTE          32865
#define ID_DT_VIEW                      32868
#define ID_DT_VIEWSOURCE                32869
#define ID_DT_LEFT                      32870
#define ID_DT_RIGHT_WITH_CHILDREN       32871
#define ID_DT_DELETE                    32872
#define ID_DT_RIGHT_ONE                 32873
#define ID_DT_RIGHT_SMART               32874
#define ID_DT_LEFT_ONE                  32875
#define ID_DT_LEFT_WITH_CHILDREN        32876
#define ID_DT_MERGE                     32877
#define ID_VIEW_FASTMODE                32878
#define ID_LAST_SCRIPT                  32899
#define ID_LAST_PLUGIN                  32900
#define ID_ADD_IMAGE                    32902
#define ID_SAVEIMG_AS                   32904
#define ID_TOOLS_SPELLCHECK             32905
#define ID_TOOLS_SPELLCHECK_HIGHLIGHT   32906
#define ID_GOTO_MATCHTAG                32907
#define ID_GOTO_WRONGTAG                32908
#define ID_TOOLS_CUSTOMIZE              32909
#define ID_HIDETOOLBAR                  32910
#define ID_EDIT_PASTE2                  0xE525
#define IDS_ENCODINGS                   61403
#define IDS_DOCUMENT_TREE_CAPTION       61404

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        256
#define _APS_NEXT_COMMAND_VALUE         32912
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           133
#endif
#endif
